export const marketBooks = [
    {
        id: 1,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 2,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 3,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 4,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 5,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 6,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 7,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 8,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 9,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 10,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 11,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 12,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 13,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 14,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 15,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 16,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 17,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 18,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 19,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 20,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
    {
        id: 21,
        cover: "https://cdn1.ozone.ru/s3/multimedia-t/wc1200/6021863837.jpg",
        name: "Война и мир",
        price: 1240,
        description: "lorem loream loreoakoa lroaokfoa rawl raworo arawl orwao rawr",
    },
];

export const marketComments = [
    {
        id: 1,
        text: "dadadadawdaw",
    },
    {
        id: 2,
        text: "dadadadawdaw",
    },
    {
        id: 3,
        text: "dadadadawdaw",
    },
    {
        id: 4,
        text: "dadadadawdaw",
    },
    {
        id: 5,
        text: "dadadadawdaw",
    },
];
